version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: teabag

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

# Distribution packages
nfpms:
  - id: packages
    package_name: teabag
    homepage: https://github.com/sivepanda/teabag
    maintainer: sivepanda
    description: TUI AppImage installer tool
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin

aurs:
  - name: teabag-bin
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/teabag-bin.git"
    skip_upload: auto
    homepage: https://github.com/sivepanda/teabag
    description: TUI AppImage installer tool
    maintainers:
      - sivepanda
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

